### ISSUE TITLE
GUI not launching: Gooey 1.0.3 requires imports

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/aggregation-for-caesar#217]
After recently updating to python3.7 and bumping many packages, I'm no longer able to launch the GUI.

```
>>> panoptes_aggregation_gui

Traceback (most recent call last):
  File "/Users/johnson/anaconda3/bin/panoptes_aggregation_gui", line 5, in <module>
    from panoptes_aggregation.scripts.gui import gui
  File "/Users/johnson/anaconda3/lib/python3.7/site-packages/panoptes_aggregation/scripts/gui.py", line 26, in <module>
    panoptes_aggregation.scripts.gui_override(gooey)
  File "/Users/johnson/anaconda3/lib/python3.7/site-packages/panoptes_aggregation/scripts/gui_overrides.py", line 43, in gui_override
    gooey.gui.components.console.Console.appendText = appendText
AttributeError: module 'gooey.gui' has no attribute 'components'
```
I rolled back gooey to 1.0.2 (currently 1.0.3 is latest) and the GUI launched successfully.  Alternately, adding a more explicit import in panoptes_aggregation/scripts/gui.py (e.g., `import gooey.gui.components.console`) will also fix this.

**Comment by lcjohnso** [comment]
Closed by #219
