### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'max_value'`

### ISSUE THREAD

**Issue by sheishistoric** [zooniverse/aggregation-for-caesar#284]
Error with progressbar occurs when attempting to extract data
  ```
(base) USERx:input userx$ panoptes_aggregation extract sorting-classifications.csv Extractor_config_workflow_4712_V163.356.yaml -o v163m356
Traceback (most recent call last):
  File "/anaconda3/bin/panoptes_aggregation", line 10, in <module>
    sys.exit(main())
File "/anaconda3/lib/python3.6/site-packages/panoptes_aggregation/scripts/aggregation_parser.py", line 284, in main
    cpu_count=args.cpu_count
  File "/anaconda3/lib/python3.6/site-packages/panoptes_aggregation/scripts/extract_panoptes_csv.py", line 122, in extract_csv
    pbar = progressbar.ProgressBar(widgets=widgets, max_value=max_pbar)
TypeError: __init__() got an unexpected keyword argument 'max_value'`
  ```

**Comment by CKrawczyk** [comment]
What version of the `progressbar2` [package](https://pypi.org/project/progressbar2/) are you using?

**Comment by sheishistoric** [comment]
progressbar2==3.39.2

**Comment by CKrawczyk** [comment]
Can you try updating to the latest version (3.50.1) and see if that helps?

**Comment by sheishistoric** [comment]
Thanks, that helped.
