### ISSUE TITLE
GUI does not launch

### ISSUE THREAD

**Issue by michaelaye** [zooniverse/aggregation-for-caesar#694]
Installed into a Python 3.10 conda env.

```bash
 ~/Dropbox/data/planet4/panoptes ❯ panoptes_aggregation_gui 
Traceback (most recent call last):
  File "/home/ayek72/mambaforge/envs/panoptes/bin/panoptes_aggregation_gui", line 5, in <module>
    from panoptes_aggregation.scripts.gui import gui
  File "/home/ayek72/mambaforge/envs/panoptes/lib/python3.10/site-packages/panoptes_aggregation/__init__.py", line 7, in <module>
    from . import reducers
  File "/home/ayek72/mambaforge/envs/panoptes/lib/python3.10/site-packages/panoptes_aggregation/reducers/__init__.py", line 3, in <module>
    from .point_reducer_hdbscan import point_reducer_hdbscan
  File "/home/ayek72/mambaforge/envs/panoptes/lib/python3.10/site-packages/panoptes_aggregation/reducers/point_reducer_hdbscan.py", line 11, in <module>
    from hdbscan import HDBSCAN
  File "/home/ayek72/mambaforge/envs/panoptes/lib/python3.10/site-packages/hdbscan/__init__.py", line 1, in <module>
    from .hdbscan_ import HDBSCAN, hdbscan
  File "/home/ayek72/mambaforge/envs/panoptes/lib/python3.10/site-packages/hdbscan/hdbscan_.py", line 509, in <module>
    memory=Memory(cachedir=None, verbose=0),
TypeError: Memory.__init__() got an unexpected keyword argument 'cachedir'
```
## Packages installed

```bash
# packages in environment at /home/ayek72/mambaforge/envs/panoptes:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
alsa-lib                  1.2.8                h166bdaf_0    conda-forge
atk-1.0                   2.38.0               hd4edc92_1    conda-forge
beautifulsoup4            4.10.0                   pypi_0    pypi
brotlipy                  0.7.0           py310h5764c6d_1005    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
cairo                     1.16.0            ha61ee94_1014    conda-forge
certifi                   2022.12.7                pypi_0    pypi
cffi                      1.15.1          py310h255011f_3    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     8.1.3                    pypi_0    pypi
collatex                  2.2                      pypi_0    pypi
colored                   1.4.4                    pypi_0    pypi
cryptography              39.0.1          py310h34c0648_0    conda-forge
cython                    0.29.33         py310heca2aa9_0    conda-forge
expat                     2.5.0                h27087fc_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
future                    0.18.2                   pypi_0    pypi
gdk-pixbuf                2.42.10              h05c8ddd_0    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
glib                      2.74.1               h6239696_1    conda-forge
glib-tools                2.74.1               h6239696_1    conda-forge
gooey                     1.0.8.1                  pypi_0    pypi
graphite2                 1.3.13            h58526e2_1001    conda-forge
gst-plugins-base          1.22.0               h4243ec0_0    conda-forge
gstreamer                 1.22.0               h25f0c4b_0    conda-forge
gtk2                      2.24.33              h90689f9_2    conda-forge
harfbuzz                  6.0.0                h8e241bc_0    conda-forge
hdbscan                   0.8.28                   pypi_0    pypi
humanize                  4.4.0                    pypi_0    pypi
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h0b41bf4_3    conda-forge
lcms2                     2.14                 hfd0df8a_1    conda-forge
ld_impl_linux-64          2.39                 hcc3a1bd_1    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
levenshtein               0.20.9          py310heca2aa9_0    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libdeflate                1.17                 h0b41bf4_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libglib                   2.74.1               h606061b_1    conda-forge
libglu                    9.0.0             he1b5a44_1001    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libsqlite                 3.40.0               h753d276_0    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libtiff                   4.5.0                h6adf6a1_2    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.10.3               h7463322_0    conda-forge
libxslt                   1.1.37               h873f0b0_0    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
lxml                      4.9.2           py310hbdc0903_0    conda-forge
markupsafe                2.1.2                    pypi_0    pypi
ncurses                   6.3                  h27087fc_1    conda-forge
networkx                  3.0                      pypi_0    pypi
numpy                     1.23.1                   pypi_0    pypi
openjpeg                  2.5.0                hfec8fc6_2    conda-forge
openssl                   3.0.8                h0b41bf4_0    conda-forge
packaging                 21.3                     pypi_0    pypi
pandas                    1.4.3                    pypi_0    pypi
pango                     1.50.13              hd33c08f_0    conda-forge
panoptes-aggregation      4.0.0                    pypi_0    pypi
panoptes-client           1.6.0                    pypi_0    pypi
panoptescli               1.1.4                    pypi_0    pypi
pathlib2                  2.3.7.post1     py310hff52083_2    conda-forge
pathvalidate              2.5.2                    pypi_0    pypi
pcre2                     10.40                hc3806b6_0    conda-forge
pillow                    9.4.0           py310h023d228_1    conda-forge
pip                       22.3.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
platformdirs              3.0.0              pyhd8ed1ab_0    conda-forge
pooch                     1.7.0              pyhd8ed1ab_0    conda-forge
prettytable               3.6.0                    pypi_0    pypi
progressbar2              4.0.0                    pypi_0    pypi
psutil                    5.9.4           py310h5764c6d_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygtrie                   2.5.0                    pypi_0    pypi
pyopenssl                 23.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9                    pypi_0    pypi
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.8          h4a9ceb5_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-levenshtein        0.12.2                   pypi_0    pypi
python-magic              0.4.27                   pypi_0    pypi
python-slugify            6.1.2                    pypi_0    pypi
python-utils              3.5.2                    pypi_0    pypi
python_abi                3.10                    3_cp310    conda-forge
pytz                      2022.7.1           pyhd8ed1ab_0    conda-forge
pyyaml                    6.0                      pypi_0    pypi
rapidfuzz                 2.13.7          py310heca2aa9_0    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
redo                      2.0.4                    pypi_0    pypi
requests                  2.28.1                   pypi_0    pypi
scikit-learn              1.1.2                    pypi_0    pypi
scipy                     1.9.0                    pypi_0    pypi
setuptools                65.6.3             pyhd8ed1ab_0    conda-forge
shapely                   1.8.2                    pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    conda-forge
soupsieve                 2.4                      pypi_0    pypi
text-unidecode            1.3                      pypi_0    pypi
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
typing-extensions         4.4.0                hd8ed1ab_0    conda-forge
typing_extensions         4.4.0              pyha770c72_0    conda-forge
tzdata                    2022g                h191b570_0    conda-forge
urllib3                   1.26.13                  pypi_0    pypi
wcwidth                   0.2.6                    pypi_0    pypi
werkzeug                  2.2.2                    pypi_0    pypi
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
wxpython                  4.2.0           py310h6b5adaf_5    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.8.4                h0b41bf4_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.5.2                h3eb15da_6    conda-forge
```

**Comment by CKrawczyk** [comment]
I think this is related to #679

**Comment by michaelaye** [comment]
indeed the import of that version of `hdbscan` simply fails within that conda env.
